#For connection examples see: http://sequel.rubyforge.org/rdoc/files/doc/opening_databases_rdoc.html

development:
  #For some reason sqlite:// for a memory table doesnt work on mac
  :primary:     development

  #For our secondary connection, we point to the prospective region inside of database.yml for your active record connections
  :secondary:   development
  :api_mode:    false

test:
  :primary:     test
  :secondary:   test
  :api_mode:    true

production:
  :primary:     production
  :secondary:   production
  :api_mode:    true